# Generated by Django 4.1.7 on 2023-03-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('short_path', models.CharField(max_length=6, unique=True)),
                ('redirect_counter', models.PositiveBigIntegerField(default=0, editable=False)),
            ],
        ),
    ]
